version: 2

jobs:
  checkout_code:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-{{ .Branch }}-{{ checksum "composer.lock" }}
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: "Set up build environment"
          command: |
            sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            echo 'export DEFAULT_COMPOSER_FLAGS: "--no-interaction --no-progress --no-suggest --prefer-dist"'
            composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo
            composer install $DEFAULT_COMPOSER_FLAGS





workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code
