version: 2.1

workflows:
  build_test_deploy:
    jobs:
      - build
      - test_phpcs:
          requires:
            - build
#      - acceptance_test_2:
#          requires:
#            - build
#      - deploy:
#          requires:
#            - acceptance_test_1
#            - acceptance_test_2


references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: /home/circleci/project/beano

  # Default container configuration.
  default_config: &default_config
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
    environment:
      - DEFAULT_COMPOSER_FLAGS: "--no-interaction --no-progress --no-suggest --prefer-dist"
    working_directory: /home/circleci/project

  # Install system dependencies.
  # DJPAULTODO: does this only need to be in the /build/ step?
  install_system_dependencies: &install_system_dependencies
    run:
      name: "Install System Dependencies"
      command: |
        sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        sudo tee -a /usr/local/etc/php/conf.d/circleci.ini \<\< EOF
        memory_limit=4096M
        error_log=/home/circleci/php.log
        EOF
        composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

jobs:
  build:
    <<: *default_config
    steps:
      - checkout:
          path: beano
      - *install_system_dependencies
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - beano
      - run: echo Hello World

  test_phpcs:
    <<: *default_config
    steps:
      - *attach_workspace
      - run:
          name: "Run PHP Code Sniffer"
          command: ls -laR
