version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers

    steps:
      - checkout
      - run: sudo apt update && sudo apt install libpq-dev
      - run: sudo docker-php-ext-install pdo pdo_pgsql pgsql

      # Download and cache dependencies
      # composer cache
      - restore_cache:
          keys:
          - composer-{{ CIRCLE_BRANCH }}-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - client-mu-plugins/vendor

      # node cache
      - restore_cache:
          keys:
            - node-v4-{{ checksum "package.json" }}
            - node-v4-
      - run: npm install
      - save_cache:
          key: node-v4-{{ checksum "package.json" }}
          paths:
            - node_modules

      # run tests with phpunit or codecept
      #- run: ./vendor/bin/phpunit
      - run: echo Hello World
      - run: echo "composer-$CIRCLE_BRANCH-"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - rake_test:
          requires:
            - bundle_dependencies
      - precompile_assets:
          requires:
            - bundle_dependencies
      - deploy:
          requires:
            - rake_test
            - precompile_assets