version: 2

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - phpcs
#          requires:
#            - build
#      - acceptance_test_2:
#          requires:
#            - build
#      - deploy:
#          requires:
#            - acceptance_test_1
#            - acceptance_test_2


# Yaml references enable us to DRY out our config by sharing variables across multiple jobs.
# In this case, we are using the "workspaces" feature to share build files across jobs.
references:
  # Working folder.
  workspace_root: &workspace_root
    /home/circleci/project

  # Subfolder of workspace_root where project repo is cloned.
  beano_project_dir: &beano_project_dir
    beano

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  # Default container configuration.
  default_config: &default_config
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
    environment:
      - DEFAULT_COMPOSER_FLAGS: "--no-interaction --no-progress --no-suggest --prefer-dist"
    working_directory: *workspace_root

  # Install system dependencies.
  # DJPAULTODO: does this only need to be in the /build/ step?
  install_system_dependencies: &install_system_dependencies
    run:
      name: "Install System Dependencies"
      command: |
        sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        sudo tee -a /usr/local/etc/php/conf.d/circleci.ini << EOF
        memory_limit=4096M
        error_log=/home/circleci/php.log
        EOF
        composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

jobs:
  build:
    <<: *default_config
    steps:
      - checkout:
          path: *beano_project_dir
      - *install_system_dependencies
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - *beano_project_dir
      - run: echo Hello World

  phpcs:
    <<: *default_config
    steps:
      - *attach_workspace
      - run:
          name: "Run PHP Code Sniffer"
          command: composer phpcs
